### ISSUE TITLE
Split multiple test modules in  testcases/mount into individual tests

### ISSUE THREAD

**Issue by Shwetha-Acharya** [samba-in-kubernetes/sit-test-cases#30]
- [ ] Consider the option of using [setup and teardown](https://stackoverflow.com/questions/7786648/how-to-call-setup-once-for-all-tests-and-teardown-after-all-are-finished) or session fixture.

**Comment by phlogistonjohn** [comment]
+1 to a fixture

**Comment by Shwetha-Acharya** [comment]
Moved parameterized Part of this issue to a new issue
