### ISSUE TITLE
 use pytest's parametrize feature for generating the various testing parameter combinations wherever required

### ISSUE THREAD

**Issue by Shwetha-Acharya** [samba-in-kubernetes/sit-test-cases#37]

**Comment by anoopcs9** [comment]
@Shwetha-Acharya Is this already implemented?

**Comment by Shwetha-Acharya** [comment]
@anoopcs9 there are still some non test functions with code repetition. Paramtrize cannot be used on them. I will add a new PR to handle them differently.

Closing this PR as changes related to parametrize are already implemented
