### ISSUE TITLE
Latest centos-ci builds for glusterfs timeout after 6 hours

### ISSUE THREAD

**Issue by xhernandez** [samba-in-kubernetes/sit-test-cases#45]
The Jenkins jobs running for glusterfs backend are failing due to timeout after 6 hours. This has been happening for few weeks.

**Comment by spuiuk** [comment]
Glusterfs testing has been disabled for now and we no longer hit the time out issues. Unfortunately Glusterfs has been EOLed and we will not be looking more deeply into the reasons for these timeout issues on disperse volumes.

Closing this open issue.
