### ISSUE TITLE
XFS: failures in smb2.create. tests

### ISSUE THREAD

**Issue by spuiuk** [samba-in-kubernetes/sit-test-cases#47]
We have encountered some failures in a few smb2.create. tests when run over xfs. This is new and has only been seen recently.

```
________________ test_smbtorture[share-xfs-default-smb2.create] ________________
Failure in running test - smb2.create
----------------------------- Captured stdout call -----------------------------
Command: /bin/smbtorture --fullname --option=torture:progress=no --option=torture:sharedelay=100000 --option=torture:writetimeupdatedelay=500000 --format=subunit --target=samba3 --user=test1%x //192.168.123.10/share-xfs-default smb2.create|/usr/bin/python3 /root/sit-test-cases/testcases/smbtorture/selftest/filter-subunit --fail-on-empty --prefix=samba3. --expected-failures=/root/sit-test-cases/testcases/smbtorture/selftest/knownfail --expected-failures=/root/sit-test-cases/testcases/smbtorture/selftest/knownfail.d --flapping=/root/sit-test-cases/testcases/smbtorture/selftest/flapping --flapping=/root/sit-test-cases/testcases/smbtorture/selftest/flapping.d --flapping=/root/sit-test-cases/testcases/smbtorture/selftest/flapping.xfs|/usr/bin/python3 /root/sit-test-cases/testcases/smbtorture/selftest/format-subunit

...

test: samba3.smb2.create.aclfile
time: 2023-11-20 15:43:07.668269Z
Testing nttrans create with sec_desc on files
basic create
adding a new ACE
creating a file with an initial ACL
time: 2023-11-20 15:43:07.689457Z
failure: samba3.smb2.create.aclfile [
Exception: (../../source4/torture/smb2/create.c:635) Incorrect status NT_STATUS_ACCESS_DENIED - should be NT_STATUS_OK

]
test: samba3.smb2.create.acldir
time: 2023-11-20 15:43:07.689467Z
Testing nttrans create with sec_desc on directories
basic create
adding a new ACE
creating a file with an initial ACL
time: 2023-11-20 15:43:07.711639Z
failure: samba3.smb2.create.acldir [
Exception: (../../source4/torture/smb2/create.c:635) Incorrect status NT_STATUS_ACCESS_DENIED - should be NT_STATUS_OK

]
test: samba3.smb2.create.nulldacl
time: 2023-11-20 15:43:07.711649Z
TESTING SEC_DESC WITH A NULL DACL
creating a file with a empty sd
get the original sd
set NULL DACL
time: 2023-11-20 15:43:07.727192Z
failure: samba3.smb2.create.nulldacl [
Exception: (../../source4/torture/smb2/create.c:1346) Incorrect status NT_STATUS_ACCESS_DENIED - should be NT_STATUS_OK

]

...

FAILED (3 failures, 0 errors and 0 unexpected successes in 0 testsuites)

```

All three are NT_STATUS_ACCESS_DENIED errors which suggest some sort of permissions problem.

**Comment by synarete** [comment]
Interesting -- I will try to reproduce over XFS on may local setup.

**Comment by anoopcs9** [comment]
Samba server logs for client:  [log.client0.txt](https://github.com/samba-in-kubernetes/sit-test-cases/files/13428651/log.client0.txt)

**Comment by anoopcs9** [comment]
Here's my analysis:

With _vfs_acl_xattr_ in place, _fget_nt_acl_ VFS call is intercepted to finally call _getxattr()_ with **CAP_DAC_OVERRIDE** set on smbd. But current SELinux allow rules for smbd under capability class doesn't include `dac_override` permission.
```
# sesearch -A -s smbd_t -t smbd_t -c capability
allow smbd_t smbd_t:capability { audit_write chown dac_read_search fowner fsetid kill lease net_admin net_bind_service setgid setuid sys_admin sys_chroot sys_nice sys_resource };
```

Thus the following AVC denial is seen in audit logs:
> type=AVC msg=audit(1700643404.314:3644): avc:  denied  { dac_override } for  pid=83444 comm="smbd[192.168.12" capability=1  scontext=system_u:system_r:smbd_t:s0 tcontext=system_u:system_r:smbd_t:s0 tclass=capability permissive=0
type=SYSCALL msg=audit(1700643404.314:3644): arch=c000003e syscall=191 success=no exit=-61 a0=7ffea4096890 a1=7f5809ce635a a2=561c6dfe9d90 a3=1000 items=1 ppid=76437 pid=83444 auid=4294967295 uid=2001 gid=0 euid=2001 suid=0 fsuid=2001 egid=2001 sgid=0 fsgid=2001 tty=(none) ses=4294967295 comm="smbd[192.168.12" exe="/usr/sbin/smbd" subj=system_u:system_r:smbd_t:s0 key=(null)ARCH=x86_64 SYSCALL=getxattr AUID="unset" UID="test1" GID="root" EUID="test1" SUID="root" FSUID="test1" EGID="test1" SGID="root" FSGID="test1"
type=CWD msg=audit(1700643404.314:3644): cwd="/samba"
type=PATH msg=audit(1700643404.314:3644): item=0 name="/proc/self/fd/32" inode=144 dev=fc:10 mode=0100775 ouid=2001 ogid=2001 rdev=00:00 obj=system_u:object_r:mnt_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="test1" OGID="test1"

and results in `NT_STATUS_ACCESS_DENIED`.

**Comment by anoopcs9** [comment]
Above analysis from https://github.com/samba-in-kubernetes/sit-test-cases/issues/47#issuecomment-1822460393 can more or less be validated by the fact that we **don't** see `NT_STATUS_ACCESS_DENIED` for [smb2.create](https://jenkins-samba.apps.ocp.cloud.ci.centos.org/job/samba_cephfs.vfs-integration-test-cases/82/consoleFull) test on CephFS via VFS where SELinux is already set to _permissive_ mode.

**Comment by anoopcs9** [comment]
> With _vfs_acl_xattr_ in place, _fget_nt_acl_ VFS call is intercepted to finally call _getxattr()_ with **CAP_DAC_OVERRIDE** set on smbd. 

_getxattr()_ call is issued for fetching `security.NTACL` which is not allowed for non-root users.

**Comment by anoopcs9** [comment]
Meanwhile necessary changes were made upstream to get back to the old behaviour of becoming root instead of just acquiring `CAP_DAC_OVERRIDE` capability to perform such privileged operations. See discussion from [!3434](https://gitlab.com/samba-team/samba/-/merge_requests/3434), [!3501](https://gitlab.com/samba-team/samba/-/merge_requests/3501) and [!3502](https://gitlab.com/samba-team/samba/-/merge_requests/3502) for detailed discussion threads.
