### ISSUE TITLE
Suggestions for improvements in SIT testcases

### ISSUE THREAD

**Issue by Shwetha-Acharya** [samba-in-kubernetes/sit-test-cases#53]
1) in _run_dbm_consistency_checks() and _check_io_consistency(), the mkdir call should have parents=False. I don't see why we should have this option set to True. A missing parent directory should be treated as an error.
2) _perform_file_operations() should perform the file operations in a sub directory to allow for easier clean up.

_Originally posted by @spuiuk in https://github.com/samba-in-kubernetes/sit-test-cases/issues/38#issuecomment-1873443604_

**Comment by Shwetha-Acharya** [comment]
This issue is taken care as part of https://github.com/samba-in-kubernetes/sit-test-cases/pull/52

**Comment by spuiuk** [comment]
Closing as these changes are merged.
